Repository ddal-kkak/ddal-kkak, pull requests merged in 2024-05, with the labels that each got.

#40 FEAT: 토스트 컴포넌트 추가
  apps/storybook/package.json
  apps/storybook/stories/atoms/button/Button.stories.tsx
  apps/storybook/stories/atoms/toast/toast.stories.tsx
  apps/storybook/stories/atoms/toast/toast.test.tsx
  packages/ui/package.json
  packages/ui/src/atoms/index.ts
  packages/ui/src/atoms/toast/index.ts
  packages/ui/src/atoms/toast/toast.tsx
  packages/ui/src/atoms/toast/toaster.tsx
  pnpm-lock.yaml
Labels: ✨ 피쳐, 🎨 퍼블리싱

#42 FIX: Storybook danger 컬러 옛날 이름으로 되어있어서 수정
  apps/storybook/stories/styles/Color.stories.tsx
  packages/ui/src/styles/colors.tsx
Labels: 🐞 버그, 🎨 퍼블리싱

#43 FEAT: 페이지 라우팅 설정
  apps/ddal-kkak/app/advanced/edit/page.tsx
  apps/ddal-kkak/app/block/edit/page.tsx
  apps/ddal-kkak/app/globals.css
  apps/ddal-kkak/app/layout.tsx
  apps/ddal-kkak/app/list/page.tsx
  apps/ddal-kkak/app/preview/page.tsx
Labels: ⚙️ 세팅

#45 페이지 정보 기본 스키마 예시 코드 추가
  apps/ddal-kkak/app/block/edit/_components/form.tsx
  apps/ddal-kkak/app/block/edit/page.tsx
  apps/ddal-kkak/package.json
  apps/ddal-kkak/schema/editor.ts
  apps/ddal-kkak/schema/index.ts
  pnpm-lock.yaml
Labels: ✨ 피쳐

#46 ddal-kkak 프로젝트 상대경로로 되어있는거 절대 경로로 수정
  apps/ddal-kkak/hooks/index.ts
  apps/ddal-kkak/lib/index.ts
  apps/ddal-kkak/schemas/README.md
  apps/ddal-kkak/tsconfig.json
  apps/ddal-kkak/types/index.ts
Labels: ⚙️ 세팅

#55 text block 추가
  apps/ddal-kkak/app/_components/blocks/index.ts
  apps/ddal-kkak/app/_components/blocks/text/index.tsx
  apps/ddal-kkak/app/_components/common/index.ts
  apps/ddal-kkak/app/_components/common/layout/default-layout.tsx
  packages/typescript-config/nextjs.json
Labels: ✨ 피쳐

#56 spacer block 추가
  apps/ddal-kkak/app/_components/blocks/index.ts
  apps/ddal-kkak/app/_components/blocks/spacer/index.tsx
Labels: ✨ 피쳐

#58 이미지 블럭 추가
  apps/ddal-kkak/app/_components/blocks/image/index.tsx
  apps/ddal-kkak/app/_components/blocks/types/image.ts
  apps/ddal-kkak/app/_components/blocks/types/index.ts
  apps/ddal-kkak/app/_components/blocks/types/style.ts
Labels: ✨ 피쳐

#61 video block 에 Key 지정 경고 수정
  apps/ddal-kkak/app/_components/blocks/video/index.tsx
Labels: 🐞 버그, ✨ 피쳐

#62 공통 패키지인 share 경로 변경
  apps/ddal-kkak/app/_components/blocks/video/index.tsx
  apps/ddal-kkak/app/_components/common/layout/default-layout.tsx
  apps/ddal-kkak/components/hook/useToggle.tsx
  apps/ddal-kkak/components/layout/Container.tsx
  apps/ddal-kkak/components/ui/HorizonLine.tsx
  apps/ddal-kkak/components/ui/icons/IconClickFill.tsx
  apps/ddal-kkak/components/ui/icons/IconClickOutline.tsx
  apps/ddal-kkak/components/ui/icons/IconDashboardFill.tsx
  apps/ddal-kkak/components/ui/icons/IconDashboardOutline.tsx
  apps/ddal-kkak/components/ui/icons/IconEditFill.tsx
  apps/ddal-kkak/components/ui/icons/IconEditOutline.tsx
  apps/ddal-kkak/components/ui/icons/IconHomeFill.tsx
  apps/ddal-kkak/components/ui/icons/IconHomeOutline.tsx
  apps/ddal-kkak/newFile.js
  packages/shared/package.json
  packages/shared/src/index.ts
  packages/shared/src/utils/index.ts
  packages/shared/utils/index.ts
  packages/ui/src/atoms/button.tsx
  packages/ui/src/atoms/input.tsx
  packages/ui/src/atoms/toast/toast.tsx
  packages/ui/src/styles/square.tsx
Labels: 🔨 리팩토링, ⚙️ 세팅

#63 Spacer block Schema 추가
  apps/ddal-kkak/app/_components/blocks/spacer/index.tsx
  apps/ddal-kkak/package.json
  apps/ddal-kkak/schemas/blocks/index.ts
  apps/ddal-kkak/schemas/blocks/spacer/index.ts
  apps/ddal-kkak/schemas/blocks/spacer/spacer.test.ts
  apps/ddal-kkak/schemas/blocks/util.ts
  apps/ddal-kkak/vitest.config.mts
  pnpm-lock.yaml
Labels: ✨ 피쳐, ⚙️ 세팅

#65 transformStringToNumber 함수 share util 로 변경
  apps/ddal-kkak/schemas/blocks/spacer/index.ts
  apps/ddal-kkak/schemas/blocks/util.ts
  packages/shared/src/utils/index.ts
Labels: 🔨 리팩토링

#66 Text block Schema 추가 했어요
  apps/ddal-kkak/app/_components/blocks/text/index.tsx
  apps/ddal-kkak/app/_components/blocks/types/style.ts
  apps/ddal-kkak/schemas/blocks/index.ts
  apps/ddal-kkak/schemas/blocks/text/index.ts
  apps/ddal-kkak/schemas/blocks/util.ts
Labels: ✨ 피쳐

#67 video block style 수정
  apps/ddal-kkak/app/_components/blocks/video/index.tsx
Labels: 🐞 버그, ✨ 피쳐, 🎨 퍼블리싱

#68 FEAT: 유틸함수로 사용할 수 있도록 코드 변경
  apps/ddal-kkak/schemas/blocks/spacer/index.ts
  apps/ddal-kkak/schemas/blocks/util.ts
Labels: 🔨 리팩토링

#73 field 추가 했습니다. (video 제외)
  apps/ddal-kkak/components/block-field/field-container.tsx
  apps/ddal-kkak/components/block-field/index.ts
  apps/ddal-kkak/components/block-field/spacer-field.tsx
  apps/ddal-kkak/components/block-field/text-field.tsx
  apps/ddal-kkak/components/editor/EditorBlocks.tsx
  apps/ddal-kkak/components/editor/EditorComponents.tsx
  apps/ddal-kkak/components/ui/field/color-field.tsx
  apps/ddal-kkak/components/ui/field/image-field.tsx
  apps/ddal-kkak/components/ui/field/index.ts
  apps/ddal-kkak/components/ui/field/input-field.tsx
  apps/ddal-kkak/components/ui/field/label.tsx
  apps/ddal-kkak/schemas/blocks/image/index.ts
  apps/ddal-kkak/schemas/blocks/index.ts
  apps/ddal-kkak/schemas/blocks/text/index.ts
  apps/ddal-kkak/schemas/editor.ts
Labels: ✨ 피쳐

#74 Input 에러 나는거 수정
  apps/ddal-kkak/components/editor/EditorBlocks.tsx
  apps/ddal-kkak/components/ui/field/color-field.tsx
  apps/ddal-kkak/components/ui/field/input-field.tsx
  apps/ddal-kkak/schemas/blocks/spacer/spacer.test.ts
  apps/ddal-kkak/schemas/blocks/util.ts
Labels: 🐞 버그
